### ISSUE TITLE
[Bug] Cannot view new graded assignments

### ISSUE THREAD

**Issue by jdtzmn** [matankb/mygann-plus#4]
I'm getting this error:

<img width="660" alt="screen shot 2019-02-11 at 7 47 05 pm" src="https://user-images.githubusercontent.com/10365982/52603686-e9abb700-2e35-11e9-8d7a-44194d3b19d5.png">

**Comment by matankb** [comment]
Thanks for reporting this bug. Oddly, this issue doesn't seem to be affecting me. Just to confirm - you're using the latest release (v1.6.0) and the issue persists after reloading? If yes, can you please send a bug report via your name > `About MyGann+` > `submit a bug report` (it can be empty, since it'll automatically send debug data).

Thanks!

**Comment by jdtzmn** [comment]
@matankb I've submitted the bug report. Tell me if you still need something else.

**Comment by matankb** [comment]
Can you try uninstalling and reinstalling?

**Comment by jdtzmn** [comment]
I tried uninstalling and reinstalling, but now the "New Graded Assignments" button just doesn't show up anymore. I've verified that the extension is still acting on the page though, because a free block appears on my schedule.

**Comment by jdtzmn** [comment]
@matankb It just showed that I got a new assignment, and the button still doesn't work.

**Comment by matankb** [comment]
That's very strange. Two things to try:

1) Can you try disabling other extensions or installing MyGann+ in a clean Chrome installation?
2) [Here is a link](https://github.com/matankb/mygann-plus/files/2950231/MyGann%2B.New.Graded.Assignments.Debug.Build.zip) to a non-minified development build. Can you try installing that and screenshotting the error? That should give slightly better diagnostics.

**Comment by jdtzmn** [comment]
@matankb closing as this is fixed in v1.7.3
